baseURL = 'https://konflux-ci.dev/'
languageCode = 'en-us'
title = 'Konflux'
theme = 'hugo-universal-theme'

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

[params]
    disabled_logo = true
    logo_text = "Konflux"

    logo = "img/logo.svg"
    logo_small = "img/logo.svg"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Want to know more?"
    link_url = "https://redhat-appstudio.github.io/docs.appstudio.io/"
    link_text = "Konflux Documentation"

[params.topbar]
    enable = true
    text = """<a href="/"><img src='img/logo.svg'></a>"""

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/konflux-ci"
    pre = "<i class='fab fa-3x fa-github'></i>"
