name: adr-index

on:
  workflow_dispatch:
  workflow_call:

jobs:
  generate-adr-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout arch repo
        uses: actions/checkout@v3
        with:
          repository: konflux-ci/architecture

      - name: Generate ADR header
        run: echo "# Architecture Decision Records (ADRs)" > index.md
        working-directory: ./ADR

      - name: Generate ADR list
        run: for adr in *.md; do title=$(head -1 $adr); echo "* [${title:2}](./$adr)" >> index.md; done
        working-directory: ./ADR

      - name: Delete self-reference to index.md
        run: sed -i '/index.md/d' index.md
        working-directory: ./ADR

      - name: Upload generated index
        uses: actions/upload-artifact@v3
        with:
          name: adr-index
          path: ./ADR/
